In [37]:
import sys
import math
import numpy as np

## Finding factors
### Bisection

In [29]:
def bisection(fx, interval, n=sys.maxsize, accuracy=None, epsilon_step=None):
    a, b = interval
    
    for i in range(n):
        f_a = fx(a)
        f_b = fx(b)

        c = (a + b)/2
        f_c = fx(c)
        
        epsilon = abs(a-b)
        
        print(f'iteration: {i}')
        print(f'a: {a}, b: {b}, c: {c}')
        print(f'f_a:{f_a}, f_b:{f_b}, f_c:{f_c}')
        print(f'interval distance: {epsilon}')
        
        print()
        
        if (f_a*f_c) < 0:
            b = c
        elif (f_b*f_c) < 0:
            a = c
            
        if accuracy:        
            if epsilon < accuracy:
                break
    if epsilon_step:
        if epsilon < epsilon_step:
            return c
    else:
        return a if abs(fx(a)) < abs(fx(b)) else b

In [30]:
def fx(x):
    return x**2 - 3

bisection(fx, (1, 2), n=7)

iteration: 0
a: 1, b: 2, c: 1.5
f_a:-2, f_b:1, f_c:-0.75
interval distance: 1

iteration: 1
a: 1.5, b: 2, c: 1.75
f_a:-0.75, f_b:1, f_c:0.0625
interval distance: 0.5

iteration: 2
a: 1.5, b: 1.75, c: 1.625
f_a:-0.75, f_b:0.0625, f_c:-0.359375
interval distance: 0.25

iteration: 3
a: 1.625, b: 1.75, c: 1.6875
f_a:-0.359375, f_b:0.0625, f_c:-0.15234375
interval distance: 0.125

iteration: 4
a: 1.6875, b: 1.75, c: 1.71875
f_a:-0.15234375, f_b:0.0625, f_c:-0.0458984375
interval distance: 0.0625

iteration: 5
a: 1.71875, b: 1.75, c: 1.734375
f_a:-0.0458984375, f_b:0.0625, f_c:0.008056640625
interval distance: 0.03125

iteration: 6
a: 1.71875, b: 1.734375, c: 1.7265625
f_a:-0.0458984375, f_b:0.008056640625, f_c:-0.01898193359375
interval distance: 0.015625



1.734375

### Newton Rhapson

In [11]:
def newton_rhapson(fx, diff_fx, n, x0):
    x_values = [x0]
    for i in range(1, n+1):
        x_values.append(x_values[i-1] - (fx(x_values[i-1])/diff_fx(x_values[i-1])))
    
    return x_values[-1]

In [12]:
def fx(x):
    return x**3 - x - 1

def diff_fx(x):
    return 3*(x**2) - 1

newton_rhapson(fx, diff_fx, 3, 1)

1.325200398950907

### Secant

In [13]:
def secant(fx, n, coord_0, coord_1):
    x0, y0 = coord_0
    x1, y1 = coord_1
    for i in range(2, n):
        print(f'iteration: {i}')
        print(f'x{i-2}: {x0:.6f}, y{i-2}: {y0:.6f}')
        print(f'x{i-1}: {x1:.6f}, y{i-1}: {y1:.6f}')
        print()
        
        new_x = x1 - (((x1 - x0) / (y1-y0))*y1)
        new_y = fx(new_x)
        
        x0, y0 = x1, y1
        x1, y1 = new_x, new_y
    
    print(f'x{n-1}: {x1:.6f}, y{n-1}: {y1:.6f}')
    return x1

In [15]:
def fx(x):
    return x**2 - 2

secant(fx, 3, (1, -1), (1.5, 0.25))

iteration: 2
x0: 1.000000, y0: -1.000000
x1: 1.500000, y1: 0.250000

x2: 1.400000, y2: -0.040000


1.4

### Regula Falsi

In [167]:
def regular_falsi(fx, interval, n=sys.maxsize, accuracy=None, epsilon_step=None):
    a, b = interval
    
    for i in range(n):
        f_a = fx(a)
        f_b = fx(b)

        c = (a*f_b - b*f_a)/(f_b-f_a)
        f_c = fx(c)
        
        epsilon = abs(a-b)
        
        print(f'iteration: {i}')
        print(f'a: {a}, b: {b}, c: {c}')
        print(f'f_a:{f_a}, f_b:{f_b}, f_c:{f_c}')
        print(f'interval distance: {epsilon}')
        
        print()
        
        if (f_a*f_c) < 0:
            b = c
        elif (f_b*f_c) < 0:
            a = c
            
        if accuracy:        
            if epsilon < accuracy:
                break
    if epsilon_step:
            if epsilon < epsilon_step:
                return c
    else:
        return a if abs(fx(a)) < abs(fx(b)) else b

In [168]:
def fx(x):
    return x**3 + x + 1

regular_falsi(fx, (-1, -0.5), n=15, accuracy=None)

iteration: 0
a: -1, b: -0.5, c: -0.6363636363636364
f_a:-1, f_b:0.375, f_c:0.10593538692712245
interval distance: 0.5

iteration: 1
a: -1, b: -0.6363636363636364, c: -0.6711956521739131
f_a:-1, f_b:0.10593538692712245, f_c:0.026428287870109646
interval distance: 0.36363636363636365

iteration: 2
a: -1, b: -0.6711956521739131, c: -0.6796616463987246
f_a:-1, f_b:0.026428287870109646, f_c:0.00637548421005496
interval distance: 0.3288043478260869

iteration: 3
a: -1, b: -0.6796616463987246, c: -0.6816910202728935
f_a:-1, f_b:0.00637548421005496, f_c:0.0015253580878831219
interval distance: 0.3203383536012754

iteration: 4
a: -1, b: -0.6816910202728935, c: -0.68217581596254
f_a:-1, f_b:0.0015253580878831219, f_c:0.000364224116321088
interval distance: 0.3183089797271065

iteration: 5
a: -1, b: -0.68217581596254, c: -0.6822915330481633
f_a:-1, f_b:0.000364224116321088, f_c:8.69279819311064e-05
interval distance: 0.31782418403746004

iteration: 6
a: -1, b: -0.6822915330481633, c: -0.682319148

-0.6823278037370069

## Interpolation
### Newton Divided

In [35]:
def _poly_newton_coefficient(x, y):
    """
    x: list or np array contanining x data points
    y: list or np array contanining y data points
    """

    m = len(x)

    x = np.copy(x)
    a = np.copy(y)
    for k in range(1, m):
        a[k:m] = (a[k:m] - a[k - 1])/(x[k:m] - x[k - 1])

    return a

def newton_polynomial(x_data, y_data, x):
    """
    x_data: data points at x
    y_data: data points at y
    x: evaluation point(s)
    """
    a = _poly_newton_coefficient(x_data, y_data)
    n = len(x_data) - 1  # Degree of polynomial
    p = a[n]

    for k in range(1, n + 1):
        p = a[n - k] + (x - x_data[n - k])*p

    return p

In [39]:
x_data = [0, 10, 15, 20, 22.5, 30]
y_data = [0, 227.04, 362.78, 517.35, 602.97, 901.67]

newton_polynomial(x_data, y_data, 16)

392.07057891555553

### Lagrange

In [53]:
def lagrange(coords, x):
    pn = 0
    n = len(coords)
    for i in range(n):
        curr_x = coords[i][0]
        curr_y = coords[i][1]
        l = 1
        for j in range(n):
            if j != i:
                check_x = coords[j][0]
                check_y = coords[j][1]
                l *= ((x - check_x) / (curr_x - check_x))
        pn += (l * curr_y)
            
    return pn

In [54]:
coords = [
    (0, 1),
    (1, 2.25),
    (2, 3.75),
    (3, 4.25)
]
    

lagrange(coords, 1.25)

2.650390625

### Least Square Method

**Linear**


In [158]:
def lsm_linear(coords, x_input):
    coords = np.array(coords)
    n = len(coords)
    x = coords[:, 0]
    y = coords[:, 1]
    sum_x = np.sum(x)
    sum_y = np.sum(y)
    sum_x2 = np.sum(np.power(x, 2))
    sum_xy = np.dot(x, y)
    
    print(f'sum of x: {sum_x}')
    print(f'sum of y: {sum_y}')
    print(f'sum of x2: {sum_x2}')
    print(f'sum of xy: {sum_xy}')
    print()
    
    array_1 = np.array([[sum_x2, -sum_x], [-sum_x, n]])
    print(array_1)
    array_2 = np.array([[sum_y], [sum_xy]])
    print(array_2)

    answer = (1/((n*sum_x2)-(sum_x*sum_x))) * np.dot(array_1, array_2)
                 
    return tuple(answer[:])

In [159]:
coords = [
    [8, 3],
    [2, 10],
    [11, 3],
    [6, 6],
    [5, 8],
    [4, 12],
    [12, 1],
    [9, 4],
    [6, 9],
    [1, 14]
]
a0, a1 = lsm_linear(coords,1)

print()
print(f'px = {a1[0]}x + ({a0[0]})')

sum of x: 64
sum of y: 70
sum of x2: 528
sum of xy: 317

[[528 -64]
 [-64  10]]
[[ 70]
 [317]]

px = -1.106418918918919x + (14.081081081081082)


**Quadratic**

In [174]:
from sympy import symbols, solve, Eq

In [199]:
def lsm_quadratic(coords, x_input):
    coords = np.array(coords)
    n = len(coords)
    x = coords[:, 0]
    y = coords[:, 1]
    sum_x = np.sum(x)
    sum_y = np.sum(y)
    sum_x2 = np.sum(np.power(x, 2))
    sum_x3 = np.sum(np.power(x, 3))
    sum_x4 = np.sum(np.power(x, 4))
    sum_xy = np.dot(x, y)
    sum_x2y = np.dot(np.power(x, 2), y)
    
    print(f'sum of x: {sum_x}')
    print(f'sum of y: {sum_y}')
    print(f'sum of x2: {sum_x2}')
    print(f'sum of x3: {sum_x3}')
    print(f'sum of x4: {sum_x4}')
    print(f'sum of xy: {sum_xy}')
    print(f'sum of x2y: {sum_x2y}')
    print()
    
    array_1 = np.array([[n, sum_x, sum_x2], 
                        [sum_x, sum_x2, sum_x3],
                        [sum_x2, sum_x3, sum_x4]
                       ])
    print(array_1)
    array_2 = np.array([[sum_y], [sum_xy], [sum_x2y]])
    print(array_2)

    a0, a1, a2 = symbols('a0 a1 a2')
    answer = solve([
        Eq(n*a0 + sum_x*a1 + sum_x2*a2, sum_y), 
        Eq(sum_x*a0 + sum_x2*a1 + sum_x3*a2, sum_xy),  
        Eq(sum_x2*a0 + sum_x3*a1 + sum_x4*a2, sum_x2y)], [a0, a1, a2])
                 
    return answer

In [200]:
coords = [
    [-1, 10],
    [0, 6],
    [1, 2],
    [2, 1],
    [3, 0],
    [4, 2],
    [5, 4],
    [6, 7],
]
answer = lsm_quadratic(coords,1)
print()
print(answer)

sum of x: 20
sum of y: 32
sum of x2: 92
sum of x3: 440
sum of x4: 2276
sum of xy: 64
sum of x2y: 400

[[   8   20   92]
 [  20   92  440]
 [  92  440 2276]]
[[ 32]
 [ 64]
 [400]]

{a0: 118/21, a1: -26/7, a2: 2/3}
