In [37]:
import sys
import math
import numpy as np

## Finding factors
### Bisection

In [257]:
def bisection(fx, interval, n=sys.maxsize, accuracy=None, epsilon_step=None):
    a, b = interval
    
    for i in range(n):
        f_a = fx(a)
        f_b = fx(b)

        c = (a + b)/2
        f_c = fx(c)
        
        epsilon = abs(a-b)
        
        print(f'iteration: {i}')
        print(f'a: {a}, b: {b}, c: {c}')
        print(f'f_a:{f_a}, f_b:{f_b}, f_c:{f_c}')
        print(f'interval distance: {epsilon}')
        
        print()
        
        if (f_a*f_c) < 0:
            b = c
        elif (f_b*f_c) < 0:
            a = c
            
        if accuracy:        
            if epsilon < accuracy:
                break
    if epsilon_step:
        if epsilon < epsilon_step:
            return c
    else:
        return a if abs(fx(a)) < abs(fx(b)) else b

In [259]:
def fx(x):
    return x**2 

bisection(fx, (-1, 1), n=3)

iteration: 0
a: -1, b: 1, c: 0.0
f_a:1, f_b:1, f_c:0.0
interval distance: 2

iteration: 1
a: -1, b: 1, c: 0.0
f_a:1, f_b:1, f_c:0.0
interval distance: 2

iteration: 2
a: -1, b: 1, c: 0.0
f_a:1, f_b:1, f_c:0.0
interval distance: 2



1

### Newton Rhapson

In [240]:
def newton_rhapson(fx, diff_fx, n, x0):
    x_values = [x0]
    for i in range(1, n+1):
        x_values.append(x_values[i-1] - (fx(x_values[i-1])/diff_fx(x_values[i-1])))
    
    return x_values[-1]

In [242]:
def fx(x):
    return x**2 - 10

def diff_fx(x):
    return 2*x

newton_rhapson(fx, diff_fx, 1, 3.1)

3.1629032258064513

### Secant

In [262]:
def secant(fx, n, coord_0, coord_1):
    x0, y0 = coord_0
    x1, y1 = coord_1
    for i in range(2, n):
        print(f'iteration: {i}')
        print(f'x{i-2}: {x0:.6f}, y{i-2}: {y0:.6f}')
        print(f'x{i-1}: {x1:.6f}, y{i-1}: {y1:.6f}')
        print()
        
        new_x = x1 - (((x1 - x0) / (y1-y0))*y1)
        new_y = fx(new_x)
        
        x0, y0 = x1, y1
        x1, y1 = new_x, new_y
    
    print(f'x{n-1}: {x1:.6f}, y{n-1}: {y1:.6f}')
    return x1

In [237]:
def fx(x):
    return x**2 - 4*x + 4

secant(fx, 3, (10, 64), (20,324))

iteration: 2
x0: 10.000000, y0: 64.000000
x1: 20.000000, y1: 324.000000

x2: 7.538462, y2: 30.674556


7.538461538461538

In [236]:
fx(20)

324

### Regula Falsi

In [263]:
def regular_falsi(fx, interval, n=sys.maxsize, accuracy=None, epsilon_step=None):
    a, b = interval
    
    for i in range(n):
        f_a = fx(a)
        f_b = fx(b)

        c = (a*f_b - b*f_a)/(f_b-f_a)
        f_c = fx(c)
        
        epsilon = abs(a-b)
        
        print(f'iteration: {i}')
        print(f'a: {a}, b: {b}, c: {c}')
        print(f'f_a:{f_a}, f_b:{f_b}, f_c:{f_c}')
        print(f'interval distance: {epsilon}')
        
        print()
        
        if (f_a*f_c) < 0:
            b = c
        elif (f_b*f_c) < 0:
            a = c
            
        if accuracy:        
            if epsilon < accuracy:
                break
    if epsilon_step:
            if epsilon < epsilon_step:
                return c
    else:
        return a if abs(fx(a)) < abs(fx(b)) else b

In [270]:
def fx(x):
    return x**3 + x + 1

regular_falsi(fx, (0, 1), n=2, accuracy=None)

iteration: 0
a: 0, b: 1, c: -0.5
f_a:1, f_b:3, f_c:0.375
interval distance: 1

iteration: 1
a: 0, b: 1, c: -0.5
f_a:1, f_b:3, f_c:0.375
interval distance: 1



0

## Interpolation
### Newton Divided

In [268]:
def _poly_newton_coefficient(x, y):
    """
    x: list or np array contanining x data points
    y: list or np array contanining y data points
    """

    m = len(x)

    x = np.copy(x)
    a = np.copy(y)
    for k in range(1, m):
        a[k:m] = (a[k:m] - a[k - 1])/(x[k:m] - x[k - 1])

    return a

def newton_polynomial(x_data, y_data, x):
    """
    x_data: data points at x
    y_data: data points at y
    x: evaluation point(s)
    """
    a = _poly_newton_coefficient(x_data, y_data)
    n = len(x_data) - 1  # Degree of polynomial
    
    p = a[n]

    for k in range(1, n + 1):
        p = a[n - k] + (x - x_data[n - k])*p

    return p

In [269]:
x_data = [4, 6, 8, 10]
y_data = [1, 3, 8, 16]

newton_polynomial(x_data, y_data, 5)

2

### Lagrange

In [250]:
def lagrange(coords, x):
    pn = 0
    n = len(coords)
    for i in range(n):
        curr_x = coords[i][0]
        curr_y = coords[i][1]
        l = 1
        for j in range(n):
            if j != i:
                check_x = coords[j][0]
                check_y = coords[j][1]
                l *= ((x - check_x) / (curr_x - check_x))
        print(l)
        print(curr_y)
        pn += (l * curr_y)
            
    return pn

In [251]:
coords = [
    (0, 1),
    (1, 0),
    (3, 4),
#     (8, 40),
#     (12, 60),
]
    

lagrange(coords, 4)

1.0
1
-2.0
0
2.0
4


9.0

### Least Square Method

**Linear**


In [228]:
def lsm_linear(coords, x_input):
    coords = np.array(coords)
    n = len(coords)
    x = coords[:, 0]
    y = coords[:, 1]
    sum_x = np.sum(x)
    sum_y = np.sum(y)
    sum_x2 = np.sum(np.power(x, 2))
    sum_xy = np.dot(x, y)
    
    print(f'sum of x: {sum_x}')
    print(f'sum of y: {sum_y}')
    print(f'sum of x2: {sum_x2}')
    print(f'sum of xy: {sum_xy}')
    print()
    
    array_1 = np.array([[sum_x2, -sum_x], [-sum_x, n]])
    print(array_1)
    array_2 = np.array([[sum_y], [sum_xy]])
    print(array_2)

    answer = (1/((n*sum_x2)-(sum_x*sum_x))) * np.dot(array_1, array_2)
                 
    return tuple(answer[:])

In [261]:
coords = [
    [1, 2],
    [2, 5],
    [3, 3],
    [4, 8],
    [5, 7],
]
a0, a1 = lsm_linear(coords,1)

print()
print(f'px = {a1[0]}x + ({a0[0]})')

sum of x: 15
sum of y: 25
sum of x2: 55
sum of xy: 88

[[ 55 -15]
 [-15   5]]
[[25]
 [88]]

px = 1.3x + (1.1)


**Quadratic**

In [174]:
from sympy import symbols, solve, Eq

In [249]:
def lsm_quadratic(coords, x_input):
    coords = np.array(coords)
    n = len(coords)
    x = coords[:, 0]
    y = coords[:, 1]
    sum_x = np.sum(x)
    sum_y = np.sum(y)
    sum_x2 = np.sum(np.power(x, 2))
    sum_x3 = np.sum(np.power(x, 3))
    sum_x4 = np.sum(np.power(x, 4))
    sum_xy = np.dot(x, y)
    sum_x2y = np.dot(np.power(x, 2), y)
    
    print(f'sum of x: {sum_x}')
    print(f'sum of y: {sum_y}')
    print(f'sum of x2: {sum_x2}')
    print(f'sum of x3: {sum_x3}')
    print(f'sum of x4: {sum_x4}')
    print(f'sum of xy: {sum_xy}')
    print(f'sum of x2y: {sum_x2y}')
    print()
    
    array_1 = np.array([[n, sum_x, sum_x2], 
                        [sum_x, sum_x2, sum_x3],
                        [sum_x2, sum_x3, sum_x4]
                       ])
    print(array_1)
    array_2 = np.array([[sum_y], [sum_xy], [sum_x2y]])
    print(array_2)

    a0, a1, a2 = symbols('a0 a1 a2')
    answer = solve([
        Eq(n*a0 + sum_x*a1 + sum_x2*a2, sum_y), 
        Eq(sum_x*a0 + sum_x2*a1 + sum_x3*a2, sum_xy),  
        Eq(sum_x2*a0 + sum_x3*a1 + sum_x4*a2, sum_x2y)], [a0, a1, a2])
                 
    return answer

In [200]:
coords = [
    [0, 10],
    [15, 6],
    [18, 2],
    [2, 1],
    [3, 0],
    [4, 2],
    [5, 4],
    [6, 7],
]
answer = lsm_quadratic(coords,1)
print()
print(answer)

sum of x: 20
sum of y: 32
sum of x2: 92
sum of x3: 440
sum of x4: 2276
sum of xy: 64
sum of x2y: 400

[[   8   20   92]
 [  20   92  440]
 [  92  440 2276]]
[[ 32]
 [ 64]
 [400]]

{a0: 118/21, a1: -26/7, a2: 2/3}
